services:
    app:
        build: .
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - db

    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: laravel_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_docker_rest_api
            MYSQL_USER: laravel
            MYSQL_PASSWORD: root
        ports:
            - "3307:3306"
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
